# intensities (requests/second)
intensity_search_LSI: 100000
intensity_update_LSI: 100000
intensity_search_GSI: 100000
intensity_update_GSI: 100000
replicaset_count: 15

# node to node latency gamma-distribution parameters
cluster_time_k: 1.5
cluster_time_theta: 0.02
# 100MB/s
cluster_net_speed: 100000000

# user to node latency gamma-distribution parameters
user_time_k: 2
user_time_theta: 0.2
# 1MB/s
user_net_speed: 1000000

# bytes
row_size: 128
# int
data_cardinality: 1000
fk_cardinality: 100

# float (ops/second)
cpu_frequency: 4000000000
mem_frequency: 10000000
# in seconds
wal_time: 0.002
timeout: 2

# btree
btree_order: 4096

